# Generated by Django 4.1.5 on 2023-02-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_ant',
            field=models.FloatField(null=True, verbose_name='Precio anterior'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True, verbose_name='Precio'),
        ),
    ]
